--Find total customers by countries
SELECT country, COUNT(customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

--Find total customers by gender
SELECT gender, COUNT(customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

--Find total products by category
SELECT COUNT(product_key) AS total_products 
FROM gold.dim_products 
GROUP BY category
ORDER BY total_products

--What is the average costs in each category? 
SELECT AVG(cost) AS Average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY Average_cost DESC

--What is the total revenue generated for each category? 
SELECT
p.category, 
SUM(fs.sales_amount) AS total_revenue
FROM gold.fact_sales fs
LEFT JOIN gold.dim_products p
ON p.product_key = fs.product_key 
GROUP BY p.category
ORDER BY total_revenue DESC

--what is total revenue generated by each customer?
SELECT fs.customer_key,
c.first_name, 
c.last_name, 
SUM(fs.sales_amount) AS total_revenue 
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers c
ON c.customer_key = fs.customer_key
GROUP BY fs.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC

--What is the distribution of sold items across countries?
SELECT country, 
COUNT(quantity) AS items_sold
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers c
ON c.customer_key = fs.customer_key
GROUP BY c.country
ORDER BY items_sold DESC
